<html>
<head>
<link rel="stylesheet" type="text/css" href="../myStyle.css"/>
<link rel="Shortcut Icon" href="../favicon.ico"/>
<title>Science and Religion <? include("ddHeader.php"); ?></title>
</head>

<style type="text/css">
u {font-weight:bold;}

</style>

<body onLoad="javascript:changeWidth();">

<script language="javascript" src="../myScript.js">
</script>
<noscript> 
<? include("tab.php"); 
tab();
?> 
</noscript>
<!-- end TAB TABLE -->

<? 
include("sidebar.php");
?>

<!-- MAIN TABLE -->

<table class="main" id="main">
<tr>
<td> 
<h1>Science And Religion</h1>
<hr>

<p>
This is an interesting study done by the <a href="http://moses.creighton.edu/JRS/toc/About.html" tagrget="_blank">Journal of Religion and Society</a>. While I'm a strong proponent of the idea that
<a href="fallacies.php#post">correlation does not necessitate causation</a>, the relationship between religiosity and societal ills needs to be explained a bit further 
than just pointing out the correlation. It could be that certain types of religious thinking hinders and/or devalues critial thinking ("critical thinking" being the 
entire focus of the "science" section of this website!), which hinders those pursuing higher education. Higher education being the keystone that eliminates high
crime, poverty, homocides, unwanted pregnancies, etc. This doesn't mean that religion <i>per se</i> is responsible.
<p>
It should also be noted that (according to Arthur C. Brooks' data in his 2006 book "Who Really Cares") religous conservatives donate 30 percent more money than 
liberals and nonreligious people to charity, are more likely to help a homeless person, and are more likely than secularists and liberals to say that they are "happy"
with life. 
<hr>
<font size="1">written by Gregory S. Paul at <a href="http://moses.creighton.edu/JRS/2005/2005-11.html" target="_blank">The Journal of Religion and Society</a></font>
<p>
<h3>Cross-National Correlations of Quantifiable Societal Health with Popular Religiosity and Secularism in the Prosperous Democracies</h3>
<p>
<ol>
<li><a href="#introduction">Introduction</a>
<li><a href="#religiosity">The Belief that Religiosity is Socially Beneficial</a>
<li><a href="#procedures">Procedures and Primary Data Sources</a>
<li><a href="#results">Results</a>
<li><a href="#conclusion">Conclusion</a>
</ol>
<u>Introduction</u><a name="introduction"></a>
<p>
[1] Two centuries ago there was relatively little dispute over the existence of God, or the societally beneficial effect of popular belief in a creator. In the 
twentieth century extensive secularization occurred in western nations, the United States being the only significant exception (Bishop; Bruce; Gill et al.; 
Sommerville). If religion has receded in some western nations, what is the impact of this unprecedented transformation upon their populations? Theists often assert 
that popular belief in a creator is instrumental towards providing the moral, ethical and other foundations necessary for a healthy, cohesive society. Many also 
contend that widespread acceptance of evolution, and/or denial of a creator, is contrary to these goals. But a cross-national study verifying these claims has yet to 
be published. That radically differing worldviews can have measurable impact upon societal conditions is plausible according to a number of mainstream researchers 
(Bainbridge; Barro; Barro and McCleary; Beeghley; Groeneman and Tobin; Huntington; Inglehart and Baker; Putman; Stark and Bainbridge). Agreement with the hypothesis 
that belief in a creator is beneficial to societies is largely based on assumption, anecdotal accounts, and on studies of limited scope and quality restricted to one 
population (Benson et al.; Hummer et al.; Idler and Kasl; Stark and Bainbridge). A partial exception is given by Barro and McCleary, who correlated economic growth 
with rates of belief in the afterlife and church attendance in numerous nations (while Kasman and Reid [2004] commented that Europe does not appear to be suffering 
unduly from its secularization). It is surprising that a more systematic examination of the question has not been previously executed since the factors required to 
do so are in place. The twentieth century acted, for the first time in human history, as a vast Darwinian global societal experiment in which a wide variety of 
dramatically differing social-religious-political-economic systems competed with one another, with varying degrees of success. A quantitative cross-national analysis 
is feasible because a large body of survey and census data on rates of religiosity, secularization, and societal indicators has become available in the prosperous 
developed democracies including the United States.
<p>
[2] This study is a first, brief look at an important subject that has been almost entirely neglected by social scientists. The primary intent is to present basic 
correlations of the elemental data. Some conclusions that can be gleaned from the plots are outlined. This is not an attempt to present a definitive study that 
establishes cause versus effect between religiosity, secularism and societal health. It is hoped that these original correlations and results will spark future 
research and debate on the issue.
<p>
<u>The Belief that Religiosity is Socially Beneficial</u><a name="religiosity"></a>
<p>
[3] As he helped initiate the American experiment Benjamin Franklin stated that “religion will be a powerful regulator of our actions, give us peace and tranquility within our minds, and render us benevolent, useful and beneficial to others” (Isaacson: 87-88). When the theory of biological evolution removed the need for a supernatural creator concerns immediately arose over the societal implications of widespread abandonment of faith (Desmond and Moore; Numbers). In 1880 the religious moralist Dostoyevsky penned the famous warning that “if God does not exist, then everything is permissible.” Even so, in Europe the issue has not been a driving focus of public and political dispute, especially since the world wars.
<p>
[4] Although its proponents often claim that anti-evolution creationism<a href="2005-11note/n1.html" target="_blank"><sup>[1]</sup></a> is scientific, it has abjectly failed in the practical realms of mainstream science and hi-tech industry (Ayala et al.; Crews; Cziko; Dawkins, 1996, 1997; Dennett; Gould; Koza et al.; L. Lane; Miller; Paul and Cox; Shanks; Wise; Young and Edis). The continuing popularity of creationism in America indicates that it is in reality a theistic social-political movement partly driven by concerns over the societal consequences of disbelief in a creator (Forrest and Gross; Numbers). The person most responsible for politicizing the issue in America, evangelical Christian W. J. Bryan,<sup>[2]</sup> expressed relatively little interest in evolution until the horrors of WW I inspired him to blame the scientific revolution that invented chemical warfare and other modern ills for “preaching that man has a brute ancestry and eliminating the miraculous and the supernatural from the Bible” (Numbers: 178).
<p>
[5] In the United States many conservative theists consider evolutionary science a leading contributor to social dysfunction because it is amoral or worse, and because it inspires disbelief in a moral creator (Colson and Pearcey; Eve and Harrold; Johnson; Numbers; Pearcey; Schroeder). The original full title for the creationist Discovery Institute was the Discovery Institute for the Renewal of Science and Culture (a title still applied to a division), and the institute’s mission challenges “materialism on specifically scientific grounds” with the intent of reversing “some of materialism’s destructive cultural consequences.” The strategy for achieving these goals is the “wedge” strategy to <a href="wedgeDoc.htm">insert intelligent design creationism into mainstream academe and subsequently destroy Darwinian science</a> (Johnson; Forrest and Gross note this effort is far behind schedule). The Discovery Institute and the less conservative, even more lavishly funded pro-theistic Templeton Foundation fund research into the existence and positive societal influence of a creator (Harris et al.; Holden). In 2000 the Discovery Institute held a neocreationist seminar for members of Congress (Applegate). Politically and socially powerful conservatives have deliberately worked to elevate popular concerns over a field of scientific and industrial research to such a level that it qualifies as a major societal fear factor. The current House majority leader T. DeLay contends that high crime rates and tragedies like the Columbine assault will continue as long schools teach children “that they are nothing but glorified apes who have evolutionized [sic] out of some primordial soup of mud” (DeLay and Dawson). Today’s leaders of the world’s largest Christian denomination, the Catholic Church, share a dim view of the social impact of evolution. In his inauguration speech, Benedict XVI lauded the benefits of belief in a creator and contended, “we are not some casual and meaningless product of evolution.” A leading church cleric and theologian (Schonborn) proclaimed that “the overwhelming evidence for purpose and design” refutes the mindless creation of Darwinian natural selection (also Dean, Dean and Goodstein).
<p>
[6] Agreement with the hypothesis that popular religiosity is societally advantageous is not limited to those opposed to evolutionary science, or to conservatives. The basic thesis can be held by anyone who believes in a benign creator regardless of the proposed mode of creation, or the believer’s social-political worldview. In broad terms the hypothesis that popular religiosity is socially beneficial holds that high rates of belief in a creator, as well as worship, prayer and other aspects of religious practice, correlate with lowering rates of lethal violence, suicide, non-monogamous sexual activity, and abortion, as well as improved physical health. Such faith-based, virtuous “cultures of life” are supposedly attainable if people believe that God created them for a special purpose, and follow the strict moral dictates imposed by religion. At one end of the spectrum are those who consider creator belief helpful but not necessarily critical to individuals and societies. At the other end the most ardent advocates consider persons and people inherently unruly and ungovernable unless they are strictly obedient to the creator (as per Barna; Colson and Pearcey; Johnson; Pearcey; Schroeder). Barro labels societal advantages that are associated with religiosity “spiritual capital,” an extension of Putman’s concept of “social capital.” The corresponding view that western secular materialism leads to “cultures of death” is the official opinion of the Papacy, which claims, “the proabortion culture is especially strong precisely where the Church’s teaching on contraception is rejected” (John Paul II). In the United States popular support for the cultural and moral superiority of theism is so extensive that popular disbelief in God ranks as another major societal fear factor.
<p>
[7] The media (Stepp) gave favorable coverage to a report that children are hardwired towards, and benefit from, accepting the existence of a divine creator on an epidemiological and neuro-scientific basis (Benson et al.). Also covered widely was a Federal report that the economic growth of nations positively responds to high rates of belief in hell and heaven.<sup>[3]</sup> Faith-based charities and education are promoted by the Bush administration<sup>[4]</sup> and religious allies and lobbies as effective means of addressing various social problems (Aronson; Goodstein). The conservative Family Research Council proclaims, “believing that God is the author of life, liberty and the family, FRC promotes the Judeo-Christian worldview as the basis for a just, free and stable society.” Towards the liberal end of the political spectrum presidential candidate Al Gore supported teaching both creationism and evolution, his running mate Joe Leiberman asserted that belief in a creator is instrumental to “secure the moral future of our nation, and raise the quality of life for all our people,” and presidential candidate John Kerry emphasized his religious values in the latter part of his campaign.
<p>
[8] With surveys showing a strong majority from conservative to liberal believing that religion is beneficial for society and for individuals, many Americans agree that their church-going nation is an exceptional, God blessed, “shining city on the hill” that stands as an impressive example for an increasingly skeptical world. But in the other developed democracies religiosity continues to decline precipitously and avowed atheists often win high office, even as clergies warn about adverse societal consequences if a revival of creator belief does not occur (Reid, 2001).
<p>
<u>Procedures and Primary Data Sources</u><a name="procedures"></a>
<p>
[9] Levels of religious and nonreligious belief and practice, and indicators of societal health and dysfunction, have been most extensively and reliably surveyed in the prosperous developed democracies (Figures 1-9). Similar data is often lacking for second and third world nations, or is less reliable. The cultural and economic similarity of the developed democracies minimizes the variability of factors outside those being examined. The approximately 800 million mostly middle class adults and children act as a massive epidemiological experiment that allows hypotheses that faith in a creator or disbelief in evolution improves or degrades societal conditions to be tested on an international scale. The extent of this data makes it potentially superior to results based on much smaller sample sizes. Data is from the 1990s, most from the middle and latter half of the decade, or the early 2000s.
<p>
[10] Data sources for rates of religious belief and practice as well as acceptance of evolution are the 1993 Environment I (Bishop) and 1998 Religion II polls conducted by the International Social Survey Program (ISSP), a cross-national collaboration on social science surveys using standard methodologies that currently involves 38 nations. The last survey interviewed approximately 23,000 people in almost all (17) of the developed democracies; Portugal is also plotted as an example of a second world European democracy. Results for western and eastern Germany are combined following the regions’ populations. England is generally Great Britain excluding Northern Ireland; Holland is all of the Netherlands. The results largely agree with national surveys on the same subjects; for example, both ISSP and Gallup indicate that absolute plus less certain believers in a higher power are about 90% of the U.S. population. The plots include Bible literalism and frequency of prayer and service attendance, as well as absolute belief in a creator, in order to examine religiosity in terms of ardency, conservatism, and activities. Self-reported rates of religious attendance and practice may be significantly higher than actual rates (Marler and Hadaway), but the data is useful for relative comparisons, especially when it parallels results on religious belief. The high rates of church attendance reported for the Swiss appear anomalous compared to their modest levels of belief and prayer.
<p>
[11] Data on aspects of societal health and dysfunction are from a variety of well-documented sources including the UN Development Programme (2000). Homicide is the best indicator of societal violence because of the extremity of the act and its unique contribution to levels of societal fear, plus the relatively reliable nature of the data (Beeghley; Neapoletan). Youth suicide (WHO) was examined in order to avoid cultural issues related to age and terminal illness. Data on STDs, teen pregnancy and birth (Panchaud et al.; Singh and Darroch) were accepted only if the compilers concluded that they were not seriously underreported, except for the U.S. where under reporting does not exaggerate disparities with the other developed democracies because they would only close the gaps. Teen pregnancy was examined in a young age class in which marriage is infrequent. Abortion data (Panchaud et al.) was accepted only from those nations in which it is as approximately legal and available as in the U.S. In order to minimize age related factors, rates of dysfunction were plotted within youth cohorts when possible.
<p>
[12] Regression analyses were not executed because of the high variability of degree of correlation, because potential causal factors for rates of societal function are complex, and because it is not the purpose of this initial study to definitively demonstrate a causal link between religion and social conditions. Nor were multivariate analyses used because they risk manipulating the data to produce errant or desired results,<sup>[5]</sup> and because the fairly consistent characteristics of the sample automatically minimizes the need to correct for external multiple factors (see further discussion below). Therefore correlations of raw data are used for this initial examination.
<p>
<u>Results</u><a name="results"></a>
<p>
[13] Among the developed democracies absolute belief in God, attendance of religious services and Bible literalism vary over a dozenfold, atheists and agnostics five fold, prayer rates fourfold, and acceptance of evolution almost twofold. Japan, Scandinavia, and France are the most secular nations in the west, the United States is the only prosperous first world nation to retain rates of religiosity otherwise limited to the second and third worlds (Bishop; PEW). Prosperous democracies where religiosity is low (which excludes the U.S.) are referred to below as secular developed democracies.
<p>
[14] Correlations between popular acceptance of human evolution and belief in and worship of a creator and Bible literalism are negative (Figure 1). The least religious nation, Japan, exhibits the highest agreement with the scientific theory, the lowest level of acceptance is found in the most religious developed democracy, the U.S.
<p>
[15] A few hundred years ago rates of homicide were astronomical in Christian Europe and the American colonies (Beeghley; R. Lane). In all secular developed democracies a centuries long-term trend has seen homicide rates drop to historical lows (Figure 2). The especially low rates in the more Catholic European states are statistical noise due to yearly fluctuations incidental to this sample, and are not consistently present in other similar tabulations (Barcley and Tavares). Despite a significant decline from a recent peak in the 1980s (Rosenfeld), the U.S. is the only prosperous democracy that retains high homicide rates, making it a strong outlier in this regard (Beeghley; Doyle, 2000). Similarly, theistic Portugal also has rates of homicides well above the secular developed democracy norm. Mass student murders in schools are rare, and have subsided somewhat since the 1990s, but the U.S. has experienced many more (National School Safety Center) than all the secular developed democracies combined. Other prosperous democracies do not significantly exceed the U.S. in rates of nonviolent and in non-lethal violent crime (Beeghley; Farrington and Langan; Neapoletan), and are often lower in this regard. The United States exhibits typical rates of youth suicide (WHO), which show little if any correlation with theistic factors in the prosperous democracies (Figure 3). The positive correlation between pro-theistic factors and juvenile mortality is remarkable, especially regarding absolute belief, and even prayer (Figure 4). Life spans tend to decrease as rates of religiosity rise (Figure 5), especially as a function of absolute belief. Denmark is the only exception. Unlike questionable small-scale epidemiological studies by Harris et al. and Koenig and Larson, higher rates of religious affiliation, attendance, and prayer do not result in lower juvenile-adult mortality rates on a cross-national basis.<sup>[6]</sup>
<p>
[16] Although the late twentieth century STD epidemic has been curtailed in all prosperous democracies (Aral and Holmes; Panchaud et al.), rates of adolescent gonorrhea infection remain six to three hundred times higher in the U.S. than in less theistic, pro-evolution secular developed democracies (Figure 6). At all ages levels are higher in the U.S., albeit by less dramatic amounts. The U.S. also suffers from uniquely high adolescent and adult syphilis infection rates, which are starting to rise again as the microbe’s resistance increases (Figure 7). The two main curable STDs have been nearly eliminated in strongly secular Scandinavia. Increasing adolescent abortion rates show positive correlation with increasing belief and worship of a creator, and negative correlation with increasing non-theism and acceptance of evolution; again rates are uniquely high in the U.S. (Figure 8). Claims that secular cultures aggravate abortion rates (John Paul II) are therefore contradicted by the quantitative data. Early adolescent pregnancy and birth have dropped in the developed democracies (Abma et al.; Singh and Darroch), but rates are two to dozens of times higher in the U.S. where the decline has been more modest (Figure 9). Broad correlations between decreasing theism and increasing pregnancy and birth are present, with Austria and especially Ireland being partial exceptions. Darroch et al. found that age of first intercourse, number of sexual partners and similar issues among teens do not exhibit wide disparity or a consistent pattern among the prosperous democracies they sampled, including the U.S. A detailed comparison of sexual practices in France and the U.S. observed little difference except that the French tend - contrary to common impression - to be somewhat more conservative (Gagnon et al.).
<p>
<u>Conclusion</u><a name="conclusion"></a>
<p>
[20] The United States’ deep social problems are all the more disturbing because the nation enjoys exceptional per capita wealth among the major western nations (Barro and McCleary; Kasman; PEW; UN Development Programme, 2000, 2004). Spending on health care is much higher as a portion of the GDP and per capita, by a factor of a third to two or more, than in any other developed democracy (UN Development Programme, 2000, 2004). The U.S. is therefore the least efficient western nation in terms of converting wealth into cultural and physical health. Understanding the reasons for this failure is urgent, and doing so requires considering the degree to which cause versus effect is responsible for the observed correlations between social conditions and religiosity versus secularism. It is therefore hoped that this initial look at a subject of pressing importance will inspire more extensive research on the subject. Pressing questions include the reasons, whether theistic or non-theistic, that the exceptionally wealthy U.S. is so inefficient that it is experiencing a much higher degree of societal distress than are less religious, less wealthy prosperous democracies. Conversely, how do the latter achieve superior societal health while having little in the way of the religious values or institutions? There is evidence that within the U.S. strong disparities in religious belief versus acceptance of evolution are correlated with similarly varying rates of societal dysfunction, the strongly theistic, anti-evolution south and mid-west having markedly worse homicide, mortality, STD, youth pregnancy, marital and related problems than the northeast where societal conditions, secularization, and acceptance of evolution approach European norms (Aral and Holmes; Beeghley, Doyle, 2002). It is the responsibility of the research community to address controversial issues and provide the information that the citizens of democracies need to chart their future courses.